<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['ID' => 1,   'Name' => 'AFGHANISTAN','Short' => ' '],
            ['ID' => 2,   'Name' => 'ALAND ISLANDS','Short' => ' '],
            ['ID' => 3,   'Name' => 'ALBANIA','Short' => ' '],
            ['ID' => 4,   'Name' => 'ALGERIA','Short' => ' '],
            ['ID' => 5,   'Name' => 'AMERICAN SAMOA','Short' => ' '],
            ['ID' => 6,   'Name' => 'ANDORRA','Short' => ' '],
            ['ID' => 7,   'Name' => 'ANGOLA','Short' => ' '],
            ['ID' => 8,   'Name' => 'ANGUILLA','Short' => ' '],
            ['ID' => 9,   'Name' => 'ANTARCTICA','Short' => ' '],
            ['ID' => 10,  'Name' => 'ANTIGUA AND BARBUDA','Short' => ' '],
            ['ID' => 11,  'Name' => 'ARGENTINA','Short' => 'ARG'],
            ['ID' => 12,  'Name' => 'ARMENIA','Short' => ' '],
            ['ID' => 13,  'Name' => 'ARUB','Short' => ' '],
            ['ID' => 14,  'Name' => 'AUSTRALIA','Short' => ' '],
            ['ID' => 15,  'Name' => 'AUSTRI','Short' => ' '],
            ['ID' => 16,  'Name' => 'AZERBAIJAN','Short' => ' '],
            ['ID' => 17,  'Name' => 'BAHAMA','Short' => ' '],
            ['ID' => 18,  'Name' => 'BAHRAIN','Short' => ' '],
            ['ID' => 19,  'Name' => 'BANGLADES','Short' => ' '],
            ['ID' => 20,  'Name' => 'BARBADOS','Short' => ' '],
            ['ID' => 21,  'Name' => 'BELARU','Short' => ' '],
            ['ID' => 22,  'Name' => 'BELGIUM','Short' => ' '],
            ['ID' => 23,  'Name' => 'BELIZ','Short' => ' '],
            ['ID' => 24,  'Name' => 'BENIN','Short' => ' '],
            ['ID' => 25,  'Name' => 'BERMUD','Short' => ' '],
            ['ID' => 26,  'Name' => 'BHUTAN','Short' => ' '],
            ['ID' => 27,  'Name' => 'BOLIVI','Short' => ' '],
            ['ID' => 28,  'Name' => 'BOSNIA AND HERZEGOVINA','Short' => ' '],
            ['ID' => 29,  'Name' => 'BOTSWAN','Short' => ' '],
            ['ID' => 31,  'Name' => 'BRAZIL','Short' => ' '],
            ['ID' => 32,  'Name' => 'BRITISH INDIAN OCEAN TERRITORY','Short' => ' '],
            ['ID' => 33,  'Name' => 'BRUNEI DARUSSALA','Short' => ' '],
            ['ID' => 34,  'Name' => 'BULGARIA','Short' => ' '],
            ['ID' => 35,  'Name' => 'BURKINA FAS','Short' => ' '],
            ['ID' => 36,  'Name' => 'BURUNDI','Short' => ' '],
            ['ID' => 37,  'Name' => 'CAMBODI','Short' => ' '],
            ['ID' => 38,  'Name' => 'CAMEROON','Short' => ' '],
            ['ID' => 39,  'Name' => 'CANADA','Short' => 'CAN'],
            ['ID' => 40,  'Name' => 'CAPE VERDE','Short' => ' '],
            ['ID' => 41,  'Name' => 'CAYMAN ISLAND','Short' => ' '],
            ['ID' => 42,  'Name' => 'CENTRAL AFRICAN REPUBLIC','Short' => ' '],
            ['ID' => 43,  'Name' => 'CHA','Short' => ' '],
            ['ID' => 44,  'Name' => 'CHILE','Short' => 'CL'],
            ['ID' => 45,  'Name' => 'CHIN','Short' => ' '],
            ['ID' => 46,  'Name' => 'CHRISTMAS ISLAND','Short' => ' '],
            ['ID' => 47,  'Name' => 'COCOS (KEELING) ISLANDS','Short' => ' '],
            ['ID' => 48,  'Name' => 'COLOMBIA','Short' => 'COL'],
            ['ID' => 49,  'Name' => 'COMORO','Short' => ' '],
            ['ID' => 50,  'Name' => 'CONGO','Short' => ' '],
            ['ID' => 51,  'Name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','Short' => ' '],
            ['ID' => 52,  'Name' => 'COOK ISLAND','Short' => ' '],
            ['ID' => 53,  'Name' => 'COSTA RICA','Short' => ' '],
            ['ID' => 54,  'Name' => "COTE D'IVOIR",'Short' => ' '],
            ['ID' => 55,  'Name' => 'CROATIA','Short' => ' '],
            ['ID' => 56,  'Name' => 'CUBA','Short' => ' '],
            ['ID' => 57,  'Name' => 'CYPRUS','Short' => ' '],
            ['ID' => 58,  'Name' => 'CZECH REPUBLI','Short' => ' '],
            ['ID' => 59,  'Name' => 'DENMARK','Short' => ' '],
            ['ID' => 60,  'Name' => 'DJIBOUTI','Short' => ' '],
            ['ID' => 61,  'Name' => 'DOMINICA','Short' => ' '],
            ['ID' => 62,  'Name' => 'DOMINICAN REPUBLI','Short' => ' '],
            ['ID' => 63,  'Name' => 'ECUADOR','Short' => ' '],
            ['ID' => 64,  'Name' => 'EGYPT','Short' => ' '],
            ['ID' => 65,  'Name' => 'EL SALVADOR','Short' => ' '],
            ['ID' => 66,  'Name' => 'EQUATORIAL GUINEA','Short' => ' '],
            ['ID' => 67,  'Name' => 'ERITREA','Short' => ' '],
            ['ID' => 68,  'Name' => 'ESTONIA','Short' => ' '],
            ['ID' => 69,  'Name' => 'ETHIOPIA','Short' => ' '],
            ['ID' => 70,  'Name' => 'FALKLAND ISLANDS(MALVINAS)','Short' => ' '],
            ['ID' => 71,  'Name' => 'FAROE ISLANDS','Short' => ' '],
            ['ID' => 72,  'Name' => 'FIJI','Short' => ' '],
            ['ID' => 73,  'Name' => 'FINLAND','Short' => ' '],
            ['ID' => 74,  'Name' => 'FRANCE','Short' => ' '],
            ['ID' => 75,  'Name' => 'FRENCH GUIANA','Short' => ' '],
            ['ID' => 76,  'Name' => 'FRENCH POLYNESIA','Short' => ' '],
            ['ID' => 77,  'Name' => 'FRENCH SOUTHERN TERRITORIES','Short' => ' '],
            ['ID' => 78,  'Name' => 'GABON','Short' => ' '],
            ['ID' => 79,  'Name' => 'GAMBIA','Short' => ' '],
            ['ID' => 80,  'Name' => 'GEORGIA','Short' => ' '],
            ['ID' => 81,  'Name' => 'GERMANY','Short' => ' '],
            ['ID' => 82,  'Name' => 'GHANA','Short' => ' '],
            ['ID' => 83,  'Name' => 'GIBRALTAR','Short' => ' '],
            ['ID' => 84,  'Name' => 'GREECE','Short' => ' '],
            ['ID' => 85,  'Name' => 'GREENLAND','Short' => ' '],
            ['ID' => 86,  'Name' => 'GRENADA','Short' => ' '],
            ['ID' => 87,  'Name' => 'GUADELOUPE','Short' => ' '],
            ['ID' => 88,  'Name' => 'GUAM','Short' => ' '],
            ['ID' => 89,  'Name' => 'GUATEMALA','Short' => ' '],
            ['ID' => 90,  'Name' => 'GUERNSEY','Short' => ' '],
            ['ID' => 91,  'Name' => 'GUINEA','Short' => ' '],
            ['ID' => 92,  'Name' => 'GUINEA-BISSAU','Short' => ' '],
            ['ID' => 93,  'Name' => 'GUYANA','Short' => ' '],
            ['ID' => 94,  'Name' => 'HAITI','Short' => ' '],
            ['ID' => 95,  'Name' => 'HEARD ISLAND AND MCDONALD ISLANDS','Short' => ' '],
            ['ID' => 96,  'Name' => 'HOLY SEE (VATICAN CITY STATE)','Short' => ' '],
            ['ID' => 97,  'Name' => 'HONDURAS','Short' => ' '],
            ['ID' => 98,  'Name' => 'HONG KONG','Short' => ' '],
            ['ID' => 99,  'Name' => 'HUNGARY','Short' => ' '],
            ['ID' => 100, 'Name' => 'ICELAND','Short' => ' '],
            ['ID' => 101, 'Name' => 'INDIA','Short' => ' '],
            ['ID' => 102, 'Name' => 'INDONESIA','Short' => ' '],
            ['ID' => 103, 'Name' => 'IRAN, ISLAMIC REPUBLIC OF','Short' => ' '],
            ['ID' => 104, 'Name' => 'IRAQ','Short' => ' '],
            ['ID' => 105, 'Name' => 'IRELAND','Short' => ' '],
            ['ID' => 106, 'Name' => 'ISLE OF MAN','Short' => ' '],
            ['ID' => 107, 'Name' => 'ISRAEL','Short' => ' '],
            ['ID' => 108, 'Name' => 'ITALY','Short' => ' '],
            ['ID' => 109, 'Name' => 'JAMAICA','Short' => ' '],
            ['ID' => 110, 'Name' => 'JAPAN','Short' => ' '],
            ['ID' => 111, 'Name' => 'JERSEY','Short' => ' '],
            ['ID' => 112, 'Name' => 'JORDAN','Short' => ' '],
            ['ID' => 113, 'Name' => 'KAZAKHSTAN','Short' => ' '],
            ['ID' => 114, 'Name' => 'KENYA','Short' => ' '],
            ['ID' => 115, 'Name' => 'KIRIBATI','Short' => ' '],
            ['ID' => 116, 'Name' => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",'Short' => ' '],
            ['ID' => 117, 'Name' => 'KOREA, REPUBLIC OF','Short' => ' '],
            ['ID' => 118, 'Name' => 'KUWAIT','Short' => ' '],
            ['ID' => 119, 'Name' => 'KYRGYZSTAN','Short' => ' '],
            ['ID' => 120, 'Name' => "LAO PEOPLE'S DEMOCRATIC REPUBLIC",'Short' => ' '],
            ['ID' => 121, 'Name' => 'LATVIA','Short' => ' '],
            ['ID' => 122, 'Name' => 'LEBANON','Short' => ' '],
            ['ID' => 123, 'Name' => 'LESOTHO','Short' => ' '],
            ['ID' => 124, 'Name' => 'LIBERIA','Short' => ' '],
            ['ID' => 125, 'Name' => 'LIBYAN ARAB JAMAHIRIYA','Short' => ' '],
            ['ID' => 126, 'Name' => 'LIECHTENSTEIN','Short' => ' '],
            ['ID' => 127, 'Name' => 'LITHUANIA','Short' => ' '],
            ['ID' => 128, 'Name' => 'LUXEMBOURG','Short' => ' '],
            ['ID' => 129, 'Name' => 'MACAO','Short' => ' '],
            ['ID' => 130, 'Name' => 'MACEDONIA','Short' => ' '],
            ['ID' => 131, 'Name' => 'MADAGASCAR','Short' => ' '],
            ['ID' => 132, 'Name' => 'MALAWI','Short' => ' '],
            ['ID' => 133, 'Name' => 'MALAYSIA','Short' => ' '],
            ['ID' => 134, 'Name' => 'MALDIVES','Short' => ' '],
            ['ID' => 135, 'Name' => 'MALI','Short' => ' '],
            ['ID' => 136, 'Name' => 'MALTA','Short' => ' '],
            ['ID' => 137, 'Name' => 'MARSHALL ISLANDS','Short' => ' '],
            ['ID' => 138, 'Name' => 'MARTINIQUE','Short' => ' '],
            ['ID' => 139, 'Name' => 'MAURITANIA','Short' => ' '],
            ['ID' => 140, 'Name' => 'MAURITIUS','Short' => ' '],
            ['ID' => 141, 'Name' => 'MAYOTTE','Short' => ' '],
            ['ID' => 142, 'Name' => 'MÉXICO','Short' => 'MEX'],
            ['ID' => 143, 'Name' => 'MICRONESIA, FEDERATED STATES OF','Short' => ' '],
            ['ID' => 144, 'Name' => 'MOLDOVA, REPUBLIC OF','Short' => ' '],
            ['ID' => 145, 'Name' => 'MONACO','Short' => ' '],
            ['ID' => 146, 'Name' => 'MONGOLIA','Short' => ' '],
            ['ID' => 147, 'Name' => 'MONTENEGRO','Short' => ' '],
            ['ID' => 148, 'Name' => 'MONTSERRAT','Short' => ' '],
            ['ID' => 149, 'Name' => 'MOROCCO','Short' => ' '],
            ['ID' => 150, 'Name' => 'MOZAMBIQUE','Short' => ' '],
            ['ID' => 151, 'Name' => 'MYANMAR','Short' => ' '],
            ['ID' => 152, 'Name' => 'NAMIBIA','Short' => ' '],
            ['ID' => 153, 'Name' => 'NAURU','Short' => ' '],
            ['ID' => 154, 'Name' => 'NEPAL','Short' => ' '],
            ['ID' => 155, 'Name' => 'NETHERLAND','Short' => ' '],
            ['ID' => 156, 'Name' => 'NETHERLANDS ANTILLES','Short' => ' '],
            ['ID' => 157, 'Name' => 'NEW CALEDONIA','Short' => ' '],
            ['ID' => 158, 'Name' => 'NEW ZEALAND','Short' => ' '],
            ['ID' => 159, 'Name' => 'NICARAGUA','Short' => ' '],
            ['ID' => 160, 'Name' => 'NIGER','Short' => ' '],
            ['ID' => 161, 'Name' => 'NIGERIA','Short' => ' '],
            ['ID' => 162, 'Name' => 'NIUE','Short' => ' '],
            ['ID' => 163, 'Name' => 'NORFOLK ISLAND','Short' => ' '],
            ['ID' => 164, 'Name' => 'NORTHERN MARIANA ISLANDS','Short' => ' '],
            ['ID' => 165, 'Name' => 'NORWAY','Short' => ' '],
            ['ID' => 166, 'Name' => 'OMAN','Short' => ' '],
            ['ID' => 167, 'Name' => 'PAKISTAN','Short' => ' '],
            ['ID' => 168, 'Name' => 'PALAU','Short' => ' '],
            ['ID' => 169, 'Name' => 'PALESTINIAN TERRITORY','Short' => ' '],
            ['ID' => 170, 'Name' => 'PANAMA','Short' => ' '],
            ['ID' => 171, 'Name' => 'PAPUA NEW GUINEA','Short' => ' '],
            ['ID' => 172, 'Name' => 'PARAGUAY','Short' => ' '],
            ['ID' => 173, 'Name' => 'PERU','Short' => ' '],
            ['ID' => 174, 'Name' => 'PHILIPPINES','Short' => ' '],
            ['ID' => 175, 'Name' => 'PITCAIRN','Short' => ' '],
            ['ID' => 176, 'Name' => 'POLAND','Short' => ' '],
            ['ID' => 177, 'Name' => 'PORTUGAL','Short' => ' '],
            ['ID' => 178, 'Name' => 'PUERTO RICO','Short' => ' '],
            ['ID' => 179, 'Name' => 'QATAR','Short' => ' '],
            ['ID' => 180, 'Name' => 'REUNION','Short' => ' '],
            ['ID' => 181, 'Name' => 'ROMANIA','Short' => ' '],
            ['ID' => 182, 'Name' => 'RUSSIAN FEDERATION','Short' => ' '],
            ['ID' => 183, 'Name' => 'RWANDA','Short' => ' '],
            ['ID' => 184, 'Name' => 'SAINT HELENA','Short' => ' '],
            ['ID' => 185, 'Name' => 'SAINT KITTS AND NEVIS','Short' => ' '],
            ['ID' => 186, 'Name' => 'SAINT LUCIA','Short' => ' '],
            ['ID' => 187, 'Name' => 'SAINT PIERRE AND MIQUELON','Short' => ' '],
            ['ID' => 188, 'Name' => 'SAINT VINCENT AND THE GRENADINES','Short' => ' '],
            ['ID' => 189, 'Name' => 'SAMOA','Short' => ' '],
            ['ID' => 190, 'Name' => 'SAN MARINO','Short' => ' '],
            ['ID' => 191, 'Name' => 'SAO TOME AND PRINCIPE','Short' => ' '],
            ['ID' => 192, 'Name' => 'SAUDI ARABIA','Short' => ' '],
            ['ID' => 194, 'Name' => 'SERBIA','Short' => ' '],
            ['ID' => 195, 'Name' => 'SEYCHELLES','Short' => ' '],
            ['ID' => 196, 'Name' => 'SIERRA LEONE','Short' => ' '],
            ['ID' => 197, 'Name' => 'SINGAPORE','Short' => ' '],
            ['ID' => 198, 'Name' => 'SLOVAKIA','Short' => ' '],
            ['ID' => 199, 'Name' => 'SLOVENIA','Short' => ' '],
            ['ID' => 200, 'Name' => 'SOLOMON ISLANDS','Short' => ' '],
            ['ID' => 201, 'Name' => 'SOMALIA','Short' => ' '],
            ['ID' => 202, 'Name' => 'SOUTH AFRICA','Short' => ' '],
            ['ID' => 203, 'Name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','Short' => ' '],
            ['ID' => 204, 'Name' => 'SPAIN','Short' => ' '],
            ['ID' => 205, 'Name' => 'SRI LANKA','Short' => ' '],
            ['ID' => 206, 'Name' => 'SUDAN','Short' => ' '],
            ['ID' => 207, 'Name' => 'SURINAME','Short' => ' '],
            ['ID' => 208, 'Name' => 'SVALBARD AND JAN MAYEN','Short' => ' '],
            ['ID' => 209, 'Name' => 'SWAZILAND','Short' => ' '],
            ['ID' => 210, 'Name' => 'SWEDEN','Short' => ' '],
            ['ID' => 211, 'Name' => 'SWITZERLAND','Short' => ' '],
            ['ID' => 212, 'Name' => 'SYRIAN ARAB REPUBLIC','Short' => ' '],
            ['ID' => 213, 'Name' => 'TAIWAN','Short' => ' '],
            ['ID' => 214, 'Name' => 'TAJIKISTAN','Short' => ' '],
            ['ID' => 215, 'Name' => 'TANZANIA, UNITED REPUBLIC OF','Short' => ' '],
            ['ID' => 216, 'Name' => 'THAILAND','Short' => ' '],
            ['ID' => 217, 'Name' => 'TIMOR-LESTE','Short' => ' '],
            ['ID' => 218, 'Name' => 'TOGO','Short' => ' '],
            ['ID' => 219, 'Name' => 'TOKELAU','Short' => ' '],
            ['ID' => 220, 'Name' => 'TONGA','Short' => ' '],
            ['ID' => 221, 'Name' => 'TRINIDAD AND TOBAGO','Short' => ' '],
            ['ID' => 222, 'Name' => 'TUNISIA','Short' => ' '],
            ['ID' => 223, 'Name' => 'TURKEY','Short' => ' '],
            ['ID' => 224, 'Name' => 'TURKMENISTAN','Short' => ' '],
            ['ID' => 225, 'Name' => 'TURKS AND CAICOS ISLANDS','Short' => ' '],
            ['ID' => 226, 'Name' => 'TUVALU','Short' => ' '],
            ['ID' => 227, 'Name' => 'UGANDA','Short' => ' '],
            ['ID' => 228, 'Name' => 'UKRAINE','Short' => ' '],
            ['ID' => 229, 'Name' => 'UNITED ARAB EMIRATES','Short' => ' '],
            ['ID' => 230, 'Name' => 'UNITED KINGDOM','Short' => ' '],
            ['ID' => 231, 'Name' => 'UNITED STATES','Short' => 'EUA'],
            ['ID' => 232, 'Name' => 'UNITED STATES MINOR OUTLYING ISLANDS','Short' => ' '],
            ['ID' => 233, 'Name' => 'URUGUAY','Short' => ' '],
            ['ID' => 234, 'Name' => 'UZBEKISTAN','Short' => ' '],
            ['ID' => 235, 'Name' => 'VANUATU','Short' => ' '],
            ['ID' => 236, 'Name' => 'VENEZUELA','Short' => ' '],
            ['ID' => 237, 'Name' => 'VIETNAM' ,'Short' => ' '],
            ['ID' => 238, 'Name' => 'VIRGIN ISLANDS, BRITISH','Short' => ' '],
            ['ID' => 239, 'Name' => 'VIRGIN ISLANDS, U.S.','Short' => ' '],
            ['ID' => 240, 'Name' => 'WALLIS AND FUTUNA','Short' => ' '],
            ['ID' => 241, 'Name' => 'WESTERN SAHARA','Short' => ' '],
            ['ID' => 242, 'Name' => 'YEMEN','Short' => ' '],
            ['ID' => 243, 'Name' => 'ZAMBIA','Short' => ' '],
            ['ID' => 244, 'Name' => 'ZIMBABWE','Short' => ' ']
        ];

        Country::insert($countries);
    }
}
