<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['ID' => 1,   'Name' => 'AFGHANISTAN'],
            ['ID' => 2,   'Name' => 'ALAND ISLANDS'],
            ['ID' => 3,   'Name' => 'ALBANIA'],
            ['ID' => 4,   'Name' => 'ALGERIA'],
            ['ID' => 5,   'Name' => 'AMERICAN SAMOA'],
            ['ID' => 6,   'Name' => 'ANDORRA'],
            ['ID' => 7,   'Name' => 'ANGOLA'],
            ['ID' => 8,   'Name' => 'ANGUILLA'],
            ['ID' => 9,   'Name' => 'ANTARCTICA'],
            ['ID' => 10,  'Name' => 'ANTIGUA AND BARBUDA'],
            ['ID' => 11,  'Name' => 'ARGENTIN'],
            ['ID' => 12,  'Name' => 'ARMENIA'],
            ['ID' => 13,  'Name' => 'ARUB'],
            ['ID' => 14,  'Name' => 'AUSTRALIA'],
            ['ID' => 15,  'Name' => 'AUSTRI'],
            ['ID' => 16,  'Name' => 'AZERBAIJAN'],
            ['ID' => 17,  'Name' => 'BAHAMA'],
            ['ID' => 18,  'Name' => 'BAHRAIN'],
            ['ID' => 19,  'Name' => 'BANGLADES'],
            ['ID' => 20,  'Name' => 'BARBADOS'],
            ['ID' => 21,  'Name' => 'BELARU'],
            ['ID' => 22,  'Name' => 'BELGIUM'],
            ['ID' => 23,  'Name' => 'BELIZ'],
            ['ID' => 24,  'Name' => 'BENIN'],
            ['ID' => 25,  'Name' => 'BERMUD'],
            ['ID' => 26,  'Name' => 'BHUTAN'],
            ['ID' => 27,  'Name' => 'BOLIVI'],
            ['ID' => 28,  'Name' => 'BOSNIA AND HERZEGOVINA'],
            ['ID' => 29,  'Name' => 'BOTSWAN'],
            ['ID' => 31,  'Name' => 'BRAZIL'],
            ['ID' => 32,  'Name' => 'BRITISH INDIAN OCEAN TERRITORY'],
            ['ID' => 33,  'Name' => 'BRUNEI DARUSSALA'],
            ['ID' => 34,  'Name' => 'BULGARIA'],
            ['ID' => 35,  'Name' => 'BURKINA FAS'],
            ['ID' => 36,  'Name' => 'BURUNDI'],
            ['ID' => 37,  'Name' => 'CAMBODI'],
            ['ID' => 38,  'Name' => 'CAMEROON'],
            ['ID' => 39,  'Name' => 'CANAD'],
            ['ID' => 40,  'Name' => 'CAPE VERDE'],
            ['ID' => 41,  'Name' => 'CAYMAN ISLAND'],
            ['ID' => 42,  'Name' => 'CENTRAL AFRICAN REPUBLIC'],
            ['ID' => 43,  'Name' => 'CHA'],
            ['ID' => 44,  'Name' => 'CHILE'],
            ['ID' => 45,  'Name' => 'CHIN'],
            ['ID' => 46,  'Name' => 'CHRISTMAS ISLAND'],
            ['ID' => 47,  'Name' => 'COCOS (KEELING) ISLANDS'],
            ['ID' => 48,  'Name' => 'COLOMBIA'],
            ['ID' => 49,  'Name' => 'COMORO'],
            ['ID' => 50,  'Name' => 'CONGO'],
            ['ID' => 51,  'Name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'],
            ['ID' => 52,  'Name' => 'COOK ISLAND'],
            ['ID' => 53,  'Name' => 'COSTA RICA'],
            ['ID' => 54,  'Name' => "COTE D'IVOIR"],
            ['ID' => 55,  'Name' => 'CROATIA'],
            ['ID' => 56,  'Name' => 'CUBA'],
            ['ID' => 57,  'Name' => 'CYPRUS'],
            ['ID' => 58,  'Name' => 'CZECH REPUBLI'],
            ['ID' => 59,  'Name' => 'DENMARK'],
            ['ID' => 60,  'Name' => 'DJIBOUTI'],
            ['ID' => 61,  'Name' => 'DOMINICA'],
            ['ID' => 62,  'Name' => 'DOMINICAN REPUBLI'],
            ['ID' => 63,  'Name' => 'ECUADOR'],
            ['ID' => 64,  'Name' => 'EGYPT'],
            ['ID' => 65,  'Name' => 'EL SALVADOR'],
            ['ID' => 66,  'Name' => 'EQUATORIAL GUINEA'],
            ['ID' => 67,  'Name' => 'ERITREA'],
            ['ID' => 68,  'Name' => 'ESTONIA'],
            ['ID' => 69,  'Name' => 'ETHIOPIA'],
            ['ID' => 70,  'Name' => 'FALKLAND ISLANDS(MALVINAS)'],
            ['ID' => 71,  'Name' => 'FAROE ISLANDS'],
            ['ID' => 72,  'Name' => 'FIJI'],
            ['ID' => 73,  'Name' => 'FINLAND'],
            ['ID' => 74,  'Name' => 'FRANCE'],
            ['ID' => 75,  'Name' => 'FRENCH GUIANA'],
            ['ID' => 76,  'Name' => 'FRENCH POLYNESIA'],
            ['ID' => 77,  'Name' => 'FRENCH SOUTHERN TERRITORIES'],
            ['ID' => 78,  'Name' => 'GABON'],
            ['ID' => 79,  'Name' => 'GAMBIA'],
            ['ID' => 80,  'Name' => 'GEORGIA'],
            ['ID' => 81,  'Name' => 'GERMANY'],
            ['ID' => 82,  'Name' => 'GHANA'],
            ['ID' => 83,  'Name' => 'GIBRALTAR'],
            ['ID' => 84,  'Name' => 'GREECE'],
            ['ID' => 85,  'Name' => 'GREENLAND'],
            ['ID' => 86,  'Name' => 'GRENADA'],
            ['ID' => 87,  'Name' => 'GUADELOUPE'],
            ['ID' => 88,  'Name' => 'GUAM'],
            ['ID' => 89,  'Name' => 'GUATEMALA'],
            ['ID' => 90,  'Name' => 'GUERNSEY'],
            ['ID' => 91,  'Name' => 'GUINEA'],
            ['ID' => 92,  'Name' => 'GUINEA-BISSAU'],
            ['ID' => 93,  'Name' => 'GUYANA'],
            ['ID' => 94,  'Name' => 'HAITI'],
            ['ID' => 95,  'Name' => 'HEARD ISLAND AND MCDONALD ISLANDS'],
            ['ID' => 96,  'Name' => 'HOLY SEE (VATICAN CITY STATE)'],
            ['ID' => 97,  'Name' => 'HONDURAS'],
            ['ID' => 98,  'Name' => 'HONG KONG'],
            ['ID' => 99,  'Name' => 'HUNGARY'],
            ['ID' => 100, 'Name' => 'ICELAND'],
            ['ID' => 101, 'Name' => 'INDIA'],
            ['ID' => 102, 'Name' => 'INDONESIA'],
            ['ID' => 103, 'Name' => 'IRAN, ISLAMIC REPUBLIC OF'],
            ['ID' => 104, 'Name' => 'IRAQ'],
            ['ID' => 105, 'Name' => 'IRELAND'],
            ['ID' => 106, 'Name' => 'ISLE OF MAN'],
            ['ID' => 107, 'Name' => 'ISRAEL'],
            ['ID' => 108, 'Name' => 'ITALY'],
            ['ID' => 109, 'Name' => 'JAMAICA'],
            ['ID' => 110, 'Name' => 'JAPAN'],
            ['ID' => 111, 'Name' => 'JERSEY'],
            ['ID' => 112, 'Name' => 'JORDAN'],
            ['ID' => 113, 'Name' => 'KAZAKHSTAN'],
            ['ID' => 114, 'Name' => 'KENYA'],
            ['ID' => 115, 'Name' => 'KIRIBATI'],
            ['ID' => 116, 'Name' => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"],
            ['ID' => 117, 'Name' => 'KOREA, REPUBLIC OF'],
            ['ID' => 118, 'Name' => 'KUWAIT'],
            ['ID' => 119, 'Name' => 'KYRGYZSTAN'],
            ['ID' => 120, 'Name' => "LAO PEOPLE'S DEMOCRATIC REPUBLIC"],
            ['ID' => 121, 'Name' => 'LATVIA'],
            ['ID' => 122, 'Name' => 'LEBANON'],
            ['ID' => 123, 'Name' => 'LESOTHO'],
            ['ID' => 124, 'Name' => 'LIBERIA'],
            ['ID' => 125, 'Name' => 'LIBYAN ARAB JAMAHIRIYA'],
            ['ID' => 126, 'Name' => 'LIECHTENSTEIN'],
            ['ID' => 127, 'Name' => 'LITHUANIA'],
            ['ID' => 128, 'Name' => 'LUXEMBOURG'],
            ['ID' => 129, 'Name' => 'MACAO'],
            ['ID' => 130, 'Name' => 'MACEDONIA'],
            ['ID' => 131, 'Name' => 'MADAGASCAR'],
            ['ID' => 132, 'Name' => 'MALAWI'],
            ['ID' => 133, 'Name' => 'MALAYSIA'],
            ['ID' => 134, 'Name' => 'MALDIVES'],
            ['ID' => 135, 'Name' => 'MALI'],
            ['ID' => 136, 'Name' => 'MALTA'],
            ['ID' => 137, 'Name' => 'MARSHALL ISLANDS'],
            ['ID' => 138, 'Name' => 'MARTINIQUE'],
            ['ID' => 139, 'Name' => 'MAURITANIA'],
            ['ID' => 140, 'Name' => 'MAURITIUS'],
            ['ID' => 141, 'Name' => 'MAYOTTE'],
            ['ID' => 142, 'Name' => 'México'],
            ['ID' => 143, 'Name' => 'MICRONESIA, FEDERATED STATES OF'],
            ['ID' => 144, 'Name' => 'MOLDOVA, REPUBLIC OF'],
            ['ID' => 145, 'Name' => 'MONACO'],
            ['ID' => 146, 'Name' => 'MONGOLIA'],
            ['ID' => 147, 'Name' => 'MONTENEGRO'],
            ['ID' => 148, 'Name' => 'MONTSERRAT'],
            ['ID' => 149, 'Name' => 'MOROCCO'],
            ['ID' => 150, 'Name' => 'MOZAMBIQUE'],
            ['ID' => 151, 'Name' => 'MYANMAR'],
            ['ID' => 152, 'Name' => 'NAMIBIA'],
            ['ID' => 153, 'Name' => 'NAURU'],
            ['ID' => 154, 'Name' => 'NEPAL'],
            ['ID' => 155, 'Name' => 'NETHERLAND'],
            ['ID' => 156, 'Name' => 'NETHERLANDS ANTILLES'],
            ['ID' => 157, 'Name' => 'NEW CALEDONIA'],
            ['ID' => 158, 'Name' => 'NEW ZEALAND'],
            ['ID' => 159, 'Name' => 'NICARAGUA'],
            ['ID' => 160, 'Name' => 'NIGER'],
            ['ID' => 161, 'Name' => 'NIGERIA'],
            ['ID' => 162, 'Name' => 'NIUE'],
            ['ID' => 163, 'Name' => 'NORFOLK ISLAND'],
            ['ID' => 164, 'Name' => 'NORTHERN MARIANA ISLANDS'],
            ['ID' => 165, 'Name' => 'NORWAY'],
            ['ID' => 166, 'Name' => 'OMAN'],
            ['ID' => 167, 'Name' => 'PAKISTAN'],
            ['ID' => 168, 'Name' => 'PALAU'],
            ['ID' => 169, 'Name' => 'PALESTINIAN TERRITORY'],
            ['ID' => 170, 'Name' => 'PANAMA'],
            ['ID' => 171, 'Name' => 'PAPUA NEW GUINEA'],
            ['ID' => 172, 'Name' => 'PARAGUAY'],
            ['ID' => 173, 'Name' => 'PERU'],
            ['ID' => 174, 'Name' => 'PHILIPPINES'],
            ['ID' => 175, 'Name' => 'PITCAIRN'],
            ['ID' => 176, 'Name' => 'POLAND'],
            ['ID' => 177, 'Name' => 'PORTUGAL'],
            ['ID' => 178, 'Name' => 'PUERTO RICO'],
            ['ID' => 179, 'Name' => 'QATAR'],
            ['ID' => 180, 'Name' => 'REUNION'],
            ['ID' => 181, 'Name' => 'ROMANIA'],
            ['ID' => 182, 'Name' => 'RUSSIAN FEDERATION'],
            ['ID' => 183, 'Name' => 'RWANDA'],
            ['ID' => 184, 'Name' => 'SAINT HELENA'],
            ['ID' => 185, 'Name' => 'SAINT KITTS AND NEVIS'],
            ['ID' => 186, 'Name' => 'SAINT LUCIA'],
            ['ID' => 187, 'Name' => 'SAINT PIERRE AND MIQUELON'],
            ['ID' => 188, 'Name' => 'SAINT VINCENT AND THE GRENADINES'],
            ['ID' => 189, 'Name' => 'SAMOA'],
            ['ID' => 190, 'Name' => 'SAN MARINO'],
            ['ID' => 191, 'Name' => 'SAO TOME AND PRINCIPE'],
            ['ID' => 192, 'Name' => 'SAUDI ARABIA'],
            ['ID' => 194, 'Name' => 'SERBIA'],
            ['ID' => 195, 'Name' => 'SEYCHELLES'],
            ['ID' => 196, 'Name' => 'SIERRA LEONE'],
            ['ID' => 197, 'Name' => 'SINGAPORE'],
            ['ID' => 198, 'Name' => 'SLOVAKIA'],
            ['ID' => 199, 'Name' => 'SLOVENIA'],
            ['ID' => 200, 'Name' => 'SOLOMON ISLANDS'],
            ['ID' => 201, 'Name' => 'SOMALIA'],
            ['ID' => 202, 'Name' => 'SOUTH AFRICA'],
            ['ID' => 203, 'Name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'],
            ['ID' => 204, 'Name' => 'SPAIN'],
            ['ID' => 205, 'Name' => 'SRI LANKA'],
            ['ID' => 206, 'Name' => 'SUDAN'],
            ['ID' => 207, 'Name' => 'SURINAME'],
            ['ID' => 208, 'Name' => 'SVALBARD AND JAN MAYEN'],
            ['ID' => 209, 'Name' => 'SWAZILAND'],
            ['ID' => 210, 'Name' => 'SWEDEN'],
            ['ID' => 211, 'Name' => 'SWITZERLAND'],
            ['ID' => 212, 'Name' => 'SYRIAN ARAB REPUBLIC'],
            ['ID' => 213, 'Name' => 'TAIWAN'],
            ['ID' => 214, 'Name' => 'TAJIKISTAN'],
            ['ID' => 215, 'Name' => 'TANZANIA, UNITED REPUBLIC OF'],
            ['ID' => 216, 'Name' => 'THAILAND'],
            ['ID' => 217, 'Name' => 'TIMOR-LESTE'],
            ['ID' => 218, 'Name' => 'TOGO'],
            ['ID' => 219, 'Name' => 'TOKELAU'],
            ['ID' => 220, 'Name' => 'TONGA'],
            ['ID' => 221, 'Name' => 'TRINIDAD AND TOBAGO'],
            ['ID' => 222, 'Name' => 'TUNISIA'],
            ['ID' => 223, 'Name' => 'TURKEY'],
            ['ID' => 224, 'Name' => 'TURKMENISTAN'],
            ['ID' => 225, 'Name' => 'TURKS AND CAICOS ISLANDS'],
            ['ID' => 226, 'Name' => 'TUVALU'],
            ['ID' => 227, 'Name' => 'UGANDA'],
            ['ID' => 228, 'Name' => 'UKRAINE'],
            ['ID' => 229, 'Name' => 'UNITED ARAB EMIRATES'],
            ['ID' => 230, 'Name' => 'UNITED KINGDOM'],
            ['ID' => 231, 'Name' => 'UNITED STATES'],
            ['ID' => 232, 'Name' => 'UNITED STATES MINOR OUTLYING ISLANDS'],
            ['ID' => 233, 'Name' => 'URUGUAY'],
            ['ID' => 234, 'Name' => 'UZBEKISTAN'],
            ['ID' => 235, 'Name' => 'VANUATU'],
            ['ID' => 236, 'Name' => 'VENEZUELA'],
            ['ID' => 237, 'Name' => 'VIETNAM'],
            ['ID' => 238, 'Name' => 'VIRGIN ISLANDS, BRITISH'],
            ['ID' => 239, 'Name' => 'VIRGIN ISLANDS, U.S.'],
            ['ID' => 240, 'Name' => 'WALLIS AND FUTUNA'],
            ['ID' => 241, 'Name' => 'WESTERN SAHARA'],
            ['ID' => 242, 'Name' => 'YEMEN'],
            ['ID' => 243, 'Name' => 'ZAMBIA'],
            ['ID' => 244, 'Name' => 'ZIMBABWE']
        ];

        Country::insert($countries);
    }
}
